//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("XenkoToolkit")]
[assembly: AssemblyDescription("A Toolkit for the Xenko game engine. Xenko version 2.1.1.1.")]
[assembly: AssemblyCompany("dfkeenan")]
[assembly: AssemblyProduct("XenkoToolkit")]
[assembly: AssemblyCopyright("Copyright © 2018")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyInformationalVersion("0.1.0.0-alpha")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]


